# Generated by Django 2.1.4 on 2018-12-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(default=None, max_length=150)),
            ],
            options={
                'verbose_name': 'Марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_title', models.CharField(default=None, max_length=200, verbose_name='Модель автомобиля*')),
                ('notes', models.TextField(blank=True, default='Нет заметок', null=True, verbose_name='Дополнительная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('brand_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculate.CarBrand', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['-brand_title'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(default=None, max_length=250, verbose_name='Название услуги')),
                ('service_price', models.PositiveIntegerField(default=0, verbose_name='Стоимость услуги')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_services', to='calculate.CarModel', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-service_title'],
            },
        ),
    ]
